### ISSUE TITLE
shifting the start day of `repr_lm`

### ISSUE THREAD

**Issue by tyokota** [PetoLau/TSrepr#1]
I have weekly data that starts on a Tuesday. The output after using the `repr_lm` function will therefore begin on Tuesday when plotting in ggplot2. Is it possible to shift the starting day to another day (i.e., I would like the plot to start on Monday). Thank you!

**Comment by PetoLau** [comment]
Hi,
I don't see logic to add mentioned feature to that function.
Just reorder outputted regression coefficients as you want.
