### ISSUE TITLE
Missing unit tests

### ISSUE THREAD

**Issue by kellieotto** [PetoLau/TSrepr#2]
This is detailed feedback for your JOSS review openjournals/joss-reviews#577.

R packages should have a `tests/` directory containing unit tests. [Hadley Wickham’s R packages book](http://r-pkgs.had.co.nz/tests.html) has a whole chapter explaining how to do this.

Better yet, you could set up a continuous integration system with [Travis CI](https://travis-ci.org) and add a badge to your README.md that shows that your package passes all of the tests.

**Comment by PetoLau** [comment]
@kellieotto I added `testthat` testings for all `repr_...()` functions.
I also created Travis CI checking for this project.
fa9e5f8

**Comment by kellieotto** [comment]
Looks great!
