### ISSUE TITLE
Paper needs to be proofread

### ISSUE THREAD

**Issue by kellieotto** [PetoLau/TSrepr#4]
This is detailed feedback for your JOSS review openjournals/joss-reviews#577.

The paper accompanying the software is unclear because it needs to be proofread for grammar and correct wording. I can give more detailed feedback if needed.

**Comment by PetoLau** [comment]
@kellieotto The paper is proofread and a part with image was added.
984e902

**Comment by kellieotto** [comment]
Much better. I would suggest one change. In the last paragraph, I think the grammar is not quite right in the first sentence. I would say "So far, no general package for time series representations computations has been created."
