### ISSUE TITLE
Unable to install TSrepr in R studio

### ISSUE THREAD

**Issue by rkahir712** [PetoLau/TSrepr#5]
when i write below line, it produces the error in loadnamespace
library("TSrepr", lib.loc="~/R/win-library/3.2")
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  namespace ‘Rcpp’ 0.12.10 is being loaded, but >= 0.12.12 is required
In addition: Warning message:
package ‘TSrepr’ was built under R version 3.5.1 
Error: package or namespace load failed for ‘TSrepr’

Help me.

**Comment by PetoLau** [comment]
Hello,
you need to have installed Rcpp (version ≥ 0.12.12), you have 0.12.10.
Also, I suggest to update your R version (it is now 3.5.1).
