### ISSUE TITLE
How to representation for many time-series data

### ISSUE THREAD

**Issue by duangrux** [PetoLau/TSrepr#6]
Dear @PetoLau 

I have 298 time-series dataset, may ask you about how do that like a return dataframe. of all time-series.

```
b_repr_df<- reinterpolate(b_lst_df[2L:298L], new.length = max(lengths(b_lst_df[2L:298L])))
b_repr_df<- repr_pla(b_lst_df[2L:298L],time=1090)
```

it will show an error like this
```
Error in repr_pla(b_lst_df[2L:297L]) : 
  (list) object cannot be coerced to type 'double'
```

but if i run one by one time-series, it is no problem.
`b_repr_df<- repr_pla(b_lst_df$coin, time= 1090, return='both')
`

**Comment by PetoLau** [comment]
Hello @duangrux 

`repr_pla` and other "repr_method" functions are working only with vectors (double).
If you want to use it for whole matrix or DF (row-wise) for extracting representations for every time series, you can use `repr_matrix` function like this and specify `repr_pla` inside it (see `?repr_matrix`):

`b_repr_df <- repr_matrix(b_lst_df[2L:298L],
                                        func = repr_pla,
                                        args = list(times = 1090, return = "both"))`

in `b_repr_df`, you will have matrix of lists with dim = N x 2 (places and points).
Best,
Peter
