### ISSUE TITLE
MASE

### ISSUE THREAD

**Issue by CooleKarotte** [PetoLau/TSrepr#7]
I saw that you calculate MASE by "error = diff / denom;". However, according to Hyndman, Koehler (2006) your "denom" should be defined as (1/ (N-m)) * sum(abs( korrekt(i) - naive(i-m))) (with m being the time-shift). I think your calculation misses this.

**Comment by PetoLau** [comment]
Good comment, but what to do when N = m, or m > N? For forecasts of seasonal time series, it is not defined really correctly.
I think, the best will be to change third argument of the `mase()` function to bench_error, for directly passing error from naive forecast (or similar).

**Comment by CooleKarotte** [comment]
Hmm you are right about this - Hyndman and Koehler do not elaborate very much about seasonality in their paper. But I had a second look at it and saw in their sum-function regarding the naive forcast, that they started with i = 2 and, hence, had to set N - 1 (page. 685).
The other formula using "N-m" is around the internet, but not mentioned by them... 

Since your calculation of the MASE takes a naive-time-series which is equal in length to the predicted time series, I think your calculation should be right after all. Sorry if I was a bit confused there!

**Comment by PetoLau** [comment]
It's alright, thank you for comment. I will make exception (stopping criterion) for lengths of real, forecast and naive arguments of `mase` function.
