### ISSUE TITLE
repr_sma unexpected output

### ISSUE THREAD

**Issue by LuisGCanales** [PetoLau/TSrepr#8]
![Captura-de-pantalla-de-2020-06-24-18-40-29](https://user-images.githubusercontent.com/31393075/85638083-96ad5b00-b64a-11ea-9df5-55b530d160f7.png)

Hi, I was using your repr_sma function but the result was not consistent with the input, then I tried it with simple examples and still got unexpected results.

**Comment by PetoLau** [comment]
Hi,
yes, I fixed this bug already, please install dev version of `TSrepr`.
Thank you
